### ISSUE TITLE
Gradlew Build: tools.jar not found

### ISSUE THREAD

**Issue by masterex1000** [apemanzilla/turbokrist#13]
I have attempted building this on windows 10 and ubuntu 14 and i have had no luck. the build fails just because of this tools.jar. This is a build failgue and i can't do a thing. I don't know how i got the error i just get it.

**Comment by apemanzilla** [comment]
This is a problem with your JDK setup. Ensure that your JAVA_HOME environment variable is set properly to point to the base path of your JDK.
