### ISSUE TITLE
Problem while building

### ISSUE THREAD

**Issue by Luca0208** [apemanzilla/turbokrist#16]
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileJava'.
> Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.895 secs
```

If you need the total stack trace please tell me, it's quite a bit.

**Comment by Lignumm** [comment]
You're probably missing the submodules.
Try this:
```
git submodule init
git submodule update
```

If that worked, clone recursively next time:
```
git clone --recursive https://github.com/apemanzilla/turbokrist.git
```

**Comment by Luca0208** [comment]
I did that, but I will try anyways had a lot of problems with git lately.

**Comment by Luca0208** [comment]
```
me.apemanzilla.jclminer.tests.TestCLConstants > testConstant_K FAILED
    com.nativelibs4java.opencl.CLBuildException

me.apemanzilla.jclminer.tests.TestCLHashing > testHashing_digest FAILED
    com.nativelibs4java.opencl.CLBuildException

me.apemanzilla.jclminer.tests.TestCLMacros > testMacro_PAD FAILED
    com.nativelibs4java.opencl.CLBuildException

me.apemanzilla.jclminer.tests.TestCLMacros > testMacro_RR FAILED
    com.nativelibs4java.opencl.CLBuildException

me.apemanzilla.jclminer.tests.TestCLMining > testMining_hashToLong FAILED
    com.nativelibs4java.opencl.CLBuildException

5 tests completed, 5 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/Luca/turbokrist/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 50.422 secs

```

**Comment by apemanzilla** [comment]
Alright that's an OpenCL problem. Can you send me a stacktrace from any of the tests in the file `file:///Users/Luca/turbokrist/build/reports/tests/index.html`

**Comment by Lignumm** [comment]
It may be worth updating your graphics drivers to see if that fixes it.

**Comment by Luca0208** [comment]
[Archiv.zip](https://github.com/apemanzilla/turbokrist/files/374280/Archiv.zip)

Afaik I have the newest drivers.

**Comment by Lignumm** [comment]
This seems to be the same issue as #9. Intel HD is already not well supported, but add Apple's weird drivers on top of that and you'll get even more trouble... either way, we don't really know what's causing this and don't have a machine to test this on either.

**Comment by apemanzilla** [comment]
Shit, it's the OSX bug again.

See #9. AFAIK there's literally nothing that we can do, this is a bug with Apple's OpenCL implementation. You can try omitting tests via `gradlew build -x test` but you'll just get the same error when you try to mine.

The only advice I can give you is to try a different OS.

**Comment by Luca0208** [comment]
Actually I get another error. Seems like Main-Class is missing in MANIFEST.MF. What is the main class?

**Comment by Lemmmy** [comment]
:egg:

**Comment by apemanzilla** [comment]
@Luca0208 the executable jar is in the `turbokrist-cli` folder.

**Comment by Luca0208** [comment]
Actually it works lol :D

**Comment by Luca0208** [comment]
Thx

**Comment by Luca0208** [comment]
If I ignore that it warms my GPU to 100°C and only gets 7 MH/s it even works perfectly lol

**Comment by apemanzilla** [comment]
what GPU is it?

**Comment by Luca0208** [comment]
It's On-Board graphics 😛 but I just compiled it to use it on my windows PC, works fine.

**Comment by Luca0208** [comment]
On windows it's like impossible to compile not even gradle works on windows(At least on mine)

**Comment by apemanzilla** [comment]
Well I compiled it on Windows so idk

`gradlew build`

**Comment by Luca0208** [comment]
Strange, but it is not your program gradle seems broken.

**Comment by Lemmmy** [comment]
sdfghjkl

**Comment by Lemmmy** [comment]
luca join slack

**Comment by Luca0208** [comment]
How? I don't know much about slack.

Should I just register?

**Comment by Luca0208** [comment]
Also do you have an e-mail or discord so we don't clutter this issue lol

**Comment by Lemmmy** [comment]
well slack is basically like discord but without voice

**Comment by Lemmmy** [comment]
give me a sec

**Comment by Luca0208** [comment]
k

**Comment by justync7** [comment]
but it has voice, just only in DMs for free teams

**Comment by Luca0208** [comment]
Btw we should really communicate by mail or something like that luca@acul.me

**Comment by Lemmmy** [comment]
i'll email you an invite soon

**Comment by Lemmmy** [comment]
just setn you a slack invite, don't be put off by the name we are changing it soon
