### ISSUE TITLE
Performance hit when launched from bash script instead of terminal

### ISSUE THREAD

**Issue by empirebuilder1** [apemanzilla/turbokrist#18]
I'm running turbokrist on Ubuntu 16.04, my laptop has a GT650m that is capable of about 33-35MH/s.  

The startup command I'm using is `java -jar turbokrist-cli.jar -h kmdni3p1au -a -w 069500862:131072`. Oracle Java 8u101 is installed from the Webupd8 PPA.

When run from the command line, turbokrist will peg one core of my i7 3630QM to 100% and have two other cores hover around 25-30%. I get the full 33-35MH/s that I expect.  

However, if the above Java command is put into a bash script called miner.sh, and run from the Linux terminal with ./miner.sh, only one CPU core is used. The rest remain idle, I hear an awful coil whine sound emanating from my laptop, and my hash rate drops to about 12-15MH/s.  

This may be a Java bug and not related to turbokrist, but I run fairly heavy Minecraft servers on this machine regularly and they have no core locks or performance issues when running from a bash script instead of the terminal.

**Comment by empirebuilder1** [comment]
I now feel like an idiot, there was a number missing from the beginning of the GPU ID string that I hadn't realized was a problem. I can't delete the issue so I'm closing it to avoid clutter.

**Comment by apemanzilla** [comment]
Just FYI, turbokrist is intended to work on discrete GPUs and not integrated graphics, and I can't make any guarantees as to whether OpenCL is using your CPU to its fullest potential.

**Comment by empirebuilder1** [comment]
I understand, the performance problem was a keyboard fumble on my part. It's running properly now, although I honestly expected a little bit more than 30Mh/s but you can't win them all. My laptop isn't very powerful to start with.
