### ISSUE TITLE
Alienware 17 2xGPU

### ISSUE THREAD

**Issue by SaddamoDeBeers** [apemanzilla/turbokrist#22]
I tried everything for a week, no success to make it run

Windows 10 64 bit

Intel HD Graphics 530
Nvidia GTX 1080

latest java 
latest SDK java 
latest nvidia drivers
got CUDA

this is the error I get all the time:

https://pastebin.com/QT9yjgVS

**Comment by Lemmmy** [comment]
Have you tried manually passing a device to it? Use `-l` to find a list of your devices, then -d to pass the comma separated device IDs e.g. `-d 1,2,3`

**Comment by SaddamoDeBeers** [comment]
it wont show me the list of the devices

**Comment by apemanzilla** [comment]
What does it do?

**Comment by SaddamoDeBeers** [comment]
I made it to work somehow, no idea what was the problem, I started from scratch...

http://imgur.com/a/d3jZB

updated windows, drivers, JAVA and everything else...

and miner started to work :D

thank you very much for help

**Comment by SaddamoDeBeers** [comment]
example command:

java -jar turbokrist-cli.jar -h krist_miner_name -d 2 -w -423801227:16777216
