### ISSUE TITLE
How to compile on a headless Linux server?

### ISSUE THREAD

**Issue by LoganDark** [apemanzilla/turbokrist#23]
Aaaaaaaaaaaa.......... it just won't work. OpenCL won't work with Java.
```
0 LD-Server ~/turbokrist ./gradlew build
:JKrist:compileJava UP-TO-DATE
:JKrist:processResources UP-TO-DATE
:JKrist:classes UP-TO-DATE
:JKrist:jar UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test

me.apemanzilla.jclminer.tests.TestCLConstants > testConstant_K FAILED
    java.lang.ExceptionInInitializerError
        Caused by: com.nativelibs4java.opencl.CLException
    java.lang.NullPointerException

me.apemanzilla.jclminer.tests.TestCLHashing > testHashing_digest FAILED
    java.lang.NoClassDefFoundError
    java.lang.NullPointerException

me.apemanzilla.jclminer.tests.TestCLMacros > testMacro_PAD FAILED
    java.lang.NoClassDefFoundError
    java.lang.NullPointerException

me.apemanzilla.jclminer.tests.TestCLMacros > testMacro_RR FAILED
    java.lang.NoClassDefFoundError
    java.lang.NullPointerException

me.apemanzilla.jclminer.tests.TestCLMining > testMining_hashToLong FAILED
    java.lang.NoClassDefFoundError
    java.lang.NullPointerException

5 tests completed, 5 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/logandark/turbokrist/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.356 secs
```
I have no idea how java development works. Can't you just provide a prebuilt jar?

**Comment by apemanzilla** [comment]
Prebuilt jar won't work without the OpenCL drivers.

**Comment by LoganDark** [comment]
I installed the OpenCL drivers though. I just can't get them to work with Java.

**Comment by apemanzilla** [comment]
If you can't get it to build then it won't run properly even with a prebuilt jar.

**Comment by LoganDark** [comment]
Sigh. I guess I'm just not supported because I don't run Windows.

**Comment by apemanzilla** [comment]
Windows is irrelevant, I use Arch Linux and have no issues.

**Comment by LoganDark** [comment]
Well, it worked once for me on Windows. That was a long time ago.

**Comment by empirebuilder1** [comment]
OpenCL drivers can be funky on Linux. I have confirmed that this works on Ubuntu- you may just have a bad driver pack.  

nVidia or AMD?

**Comment by LoganDark** [comment]
My server doesn't have a GPU, only integrated graphics.

**Comment by empirebuilder1** [comment]
Then there's your problem. Most of the time iGPU's don't have openCL support, and the few Intel implementations that do are rudimentary (and slow) at best, or somewhat nonfunctional at worst (ala Linux).

**Comment by BTCTaras** [comment]
If you're trying to mine with integrated graphics, you may be better off CPU mining. [1lann's miner](https://github.com/1lann/krist-miner) is highly optimized and on some hardware could probably outperform a GPU running turbokrist.

**Comment by LoganDark** [comment]
Been mining with that miner with 2 spare machines (and occasionally my personal laptop, which outperforms both of them) for days.
