### ISSUE TITLE
Could not find tools.jar

### ISSUE THREAD

**Issue by RAS-music** [apemanzilla/turbokrist#27]
C:\Users\X\OneDrive\Documenten\GitHub\turbokrist>gradlew build
:JKrist:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':JKrist:compileJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.004 secs

**Comment by apemanzilla** [comment]
https://github.com/apemanzilla/turbokrist/issues/13#issuecomment-188811458
