### ISSUE TITLE
Build or Mining wiki pages out of date?

### ISSUE THREAD

**Issue by lupus590** [apemanzilla/turbokrist#28]
**Description**
Ran `gradlew.bat build` on Windows 10 and did not get `build/libs/turbokrist-cli.jar`  got `build/libs/turbokrist.jar` which did not work with the [Mining](https://github.com/apemanzilla/turbokrist/wiki/Mining-Krist) wiki page.

**Expected Behavior**

Running `gradlew.bat build` produces `build/libs/turbokrist-cli.jar` as described in the [Building](https://github.com/apemanzilla/turbokrist/wiki/Building) page of the wiki

**Steps to reproduce**

Follow instructions on the wiki.

**Other Information**

[Hardware info](https://pastebin.com/DqgYHAU0)

Off topic, you may want to look at this: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by Lemmmy** [comment]
yeah they do: ![](https://shitty.download/7kh5.png)

**Comment by apemanzilla** [comment]
On a side note congrats, we added a label because of this issue

**Comment by lupus590** [comment]
In my defence, it was 11-something pm.
