### ISSUE TITLE
turbokrist on mac

### ISSUE THREAD

**Issue by aarock1234** [apemanzilla/turbokrist#29]
Gets stuck on 33% when building

**Comment by apemanzilla** [comment]
That doesn't really tell me anything.

**Comment by aarock1234** [comment]
WELL, the issue is this.

i run "sudo ./gradlew build"
and then it gets stuck on
`:JKrist:compileJava UP-TO-DATE
:JKrist:processResources UP-TO-DATE
:JKrist:classes UP-TO-DATE
:JKrist:jar UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
> Building 33% > :test
`
And doesnt move. It stays like that

**Comment by apemanzilla** [comment]
Duplicate of #9
